"""add management_entity to asset

Revision ID: ca5d6adb0012
Revises: 20250120_add_security_events
Create Date: 2026-01-24 11:11:33.734151

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca5d6adb0012"
down_revision: str | None = "20250120_add_security_events"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)
    if inspector.has_table("assets"):
        columns = {column["name"] for column in inspector.get_columns("assets")}
        if "management_entity" not in columns:
            op.add_column(
                "assets",
                sa.Column(
                    "management_entity",
                    sa.String(length=200),
                    nullable=True,
                    comment="经营管理单位",
                ),
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_property_owners_owner_type"),
        "property_owners",
        ["owner_type"],
        unique=False,
    )
    op.create_index(
        op.f("idx_property_owners_organization_id"),
        "property_owners",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_property_owners_name"), "property_owners", ["name"], unique=False
    )
    op.drop_column("notifications", "updated_at")
    op.drop_column("notifications", "created_at")
    op.drop_column("assets", "management_entity")
    op.create_table(
        "extraction_feedback",
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("template_id", sa.VARCHAR(), nullable=False),
        sa.Column("version_id", sa.VARCHAR(), nullable=True),
        sa.Column("doc_type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("file_path", sa.VARCHAR(length=500), nullable=True),
        sa.Column("session_id", sa.VARCHAR(length=100), nullable=True),
        sa.Column("field_name", sa.VARCHAR(length=100), nullable=True),
        sa.Column("original_value", sa.TEXT(), nullable=True),
        sa.Column("corrected_value", sa.TEXT(), nullable=True),
        sa.Column("confidence_before", sa.FLOAT(), nullable=True),
        sa.Column("user_action", sa.VARCHAR(length=50), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["prompt_templates.id"],
            name=op.f("extraction_feedback_template_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["prompt_versions.id"],
            name=op.f("extraction_feedback_version_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_extraction_feedback_template_id"),
        "extraction_feedback",
        ["template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extraction_feedback_created_at"),
        "extraction_feedback",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "prompt_templates",
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("doc_type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("provider", sa.VARCHAR(length=50), nullable=False),
        sa.Column("description", sa.VARCHAR(length=500), nullable=True),
        sa.Column("system_prompt", sa.TEXT(), nullable=False),
        sa.Column("user_prompt_template", sa.TEXT(), nullable=False),
        sa.Column("few_shot_examples", sqlite.JSON(), nullable=True),
        sa.Column("version", sa.VARCHAR(length=20), nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), nullable=False),
        sa.Column("tags", sqlite.JSON(), nullable=True),
        sa.Column("avg_accuracy", sa.FLOAT(), nullable=True),
        sa.Column("avg_confidence", sa.FLOAT(), nullable=True),
        sa.Column("total_usage", sa.INTEGER(), nullable=True),
        sa.Column("current_version_id", sa.VARCHAR(), nullable=True),
        sa.Column("parent_id", sa.VARCHAR(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.Column("created_by", sa.VARCHAR(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["current_version_id"],
            ["prompt_versions.id"],
            name=op.f("prompt_templates_current_version_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["prompt_templates.id"],
            name=op.f("prompt_templates_parent_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name=op.f("uq_prompt_templates_name")),
    )
    op.create_index(
        op.f("ix_prompt_templates_status"), "prompt_templates", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_prompt_templates_provider"),
        "prompt_templates",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_templates_doc_type"),
        "prompt_templates",
        ["doc_type"],
        unique=False,
    )
    op.create_table(
        "prompt_versions",
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("template_id", sa.VARCHAR(), nullable=False),
        sa.Column("version", sa.VARCHAR(length=20), nullable=False),
        sa.Column("system_prompt", sa.TEXT(), nullable=False),
        sa.Column("user_prompt_template", sa.TEXT(), nullable=False),
        sa.Column("few_shot_examples", sqlite.JSON(), nullable=True),
        sa.Column("change_description", sa.VARCHAR(length=500), nullable=True),
        sa.Column("change_type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("auto_generated", sa.BOOLEAN(), nullable=True),
        sa.Column("accuracy", sa.FLOAT(), nullable=True),
        sa.Column("confidence", sa.FLOAT(), nullable=True),
        sa.Column("usage_count", sa.INTEGER(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("created_by", sa.VARCHAR(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["prompt_templates.id"],
            name=op.f("prompt_versions_template_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prompt_versions_template_id"),
        "prompt_versions",
        ["template_id"],
        unique=False,
    )
    op.create_table(
        "prompt_metrics",
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("template_id", sa.VARCHAR(), nullable=False),
        sa.Column("version_id", sa.VARCHAR(), nullable=True),
        sa.Column("date", sa.DATE(), nullable=False),
        sa.Column("total_extractions", sa.INTEGER(), nullable=True),
        sa.Column("successful_extractions", sa.INTEGER(), nullable=True),
        sa.Column("corrected_fields", sa.INTEGER(), nullable=True),
        sa.Column("avg_accuracy", sa.FLOAT(), nullable=True),
        sa.Column("avg_confidence", sa.FLOAT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["prompt_templates.id"],
            name=op.f("prompt_metrics_template_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["prompt_versions.id"],
            name=op.f("prompt_metrics_version_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prompt_metrics_template_id"),
        "prompt_metrics",
        ["template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_metrics_template_date"),
        "prompt_metrics",
        ["template_id", "date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_metrics_date"), "prompt_metrics", ["date"], unique=False
    )
    # ### end Alembic commands ###
