"""Shared file size constants (bytes)."""

MB = 1024 * 1024

DEFAULT_MAX_FILE_SIZE = 50 * MB
DEFAULT_MAX_EXCEL_FILE_SIZE = 100 * MB
DEFAULT_MAX_IMAGE_FILE_SIZE = 20 * MB
DEFAULT_MAX_GENERIC_FILE_SIZE = 10 * MB
DEFAULT_MAX_ARCHIVE_FILE_SIZE = 200 * MB
MAX_FILE_SIZE_LIMIT = 500 * MB
MIN_FILE_SIZE_BYTES = 1024
