"""Security monitoring constants."""

TOKEN_BLACKLIST_DEGRADE_WINDOW_SECONDS = 300
TOKEN_BLACKLIST_DEGRADE_THRESHOLD = 3
TOKEN_BLACKLIST_ERROR_WINDOW_SECONDS = 300
TOKEN_BLACKLIST_ERROR_THRESHOLD = 3
