"""Shared timeout constants (seconds)."""

TASK_QUEUE_POLL_TIMEOUT_SECONDS = 1
WECOM_REQUEST_TIMEOUT_SECONDS = 10.0
REDIS_SOCKET_CONNECT_TIMEOUT_SECONDS = 5
REDIS_SOCKET_TIMEOUT_SECONDS = 5
DEFAULT_LLM_TIMEOUT_SECONDS = 30
DEFAULT_LLM_COMPAT_TIMEOUT_SECONDS = 60
